import boy from './assets/boy.png'
import girl from './assets/girl.png'

const ContributorData = [
  {
    id: 1,
    name: "Aman Chopra",
    img: boy,
    skill1: "MERN Developer",
    skill2: "Java",
    skill3: "Cloud (AWS)",
    skill4: "DevOps",
    l_link: "https://www.linkedin.com/in/aman-chopra-375a81171/",
    g_link: "https://github.com/Aman1905",
    t_link: "https://twitter.com/iam_chopra_aman",
  },

  {
    id: 2,
    name: "Priya Sharma",
    img: girl,
    skill1: "Python3",
    skill2: "C++",
    skill3: "Data Science",
    skill4: "Cloud (AWS)",
    l_link: "https://www.linkedin.com/in/devprisha/",
    g_link: "https://github.com/DevPriSha",
  },
  {
    id: 3,
    img: boy,
    name: "Priyanshu Haldar",
    skill1: "Frontend",
    skill2: "Heroku",
    skill3: "MongoDB",
    skill4: "Java",
    l_link: "https://www.linkedin.com/in/priyanshu-haldar-61b2731aa/",
    g_link: "https://github.com/priyanshuhaldar007",
    t_link: "https://twitter.com/PriyanshuHalda5" ,
  },

  {
    id: 4,
    img: girl,
    name:"Sonal Singh",
    skill1:"Java",
    skill2:"HTML",
    skill3:"CSS",
    skill4:"Bootstrap",
    l_link:"https://www.linkedin.com/in/sonalsingh25/",
    g_link:"https://github.com/sonalsingh25",
    t_link:"https://twitter.com/sonalsingh_77" ,
  },

  {
    id: 5,
    img: boy,
    name:"Aniket Singh",
    skill1:"C++",
    skill2:"HTML",
    skill3:"Js",
    skill4:"Bootstrap",
    l_link:"https://www.linkedin.com/in/aniket-singh-23b1101a8/",
    g_link:"https://github.com/Aniketsingh1411",
    t_link:"https://twitter.com/AniketS71180497?s=09",
  },

  {
    id: 6,
    img: girl,
    name:"Nilisha Jaiswal",
    skill1:"Web Developer",
    skill2:"C++",
    skill3:"Js",
    skill4:"DevOps",
    l_link:"https://www.linkedin.com/in/nilisha-jaiswal-7980061b2/",
    g_link:"https://github.com/nilisha-jais",
    t_link:"https://twitter.com/jaiswal_nilu05",
  },

  {
    id: 7,
    img: boy,
    name:"Shivanand Kundargi",
    skill1:"HTML",
    skill2:"C++",
    skill3:"Css",
    skill4:"python",
    g_link:"https://github.com/shivanandkundargi",
  },

  {
    id: 8,
    img: girl,
    name:"Sahana J",
    skill1:"HTML",
    skill2:"CSS",
    skill3:"Js(basics)",
    skill4:"Python",
    l_link:"https://www.linkedin.com/in/sahanajayakumar01/",
    g_link:"https://github.com/Sahanajayakumar",
  },
  {
    id: 9,
    img: boy,
    name: "Prasanth Grandhe",
    skill1: "Web Developer",
    skill2: "C+",
    skill3: "Js",
    skill4: "HTML",
    l_link: "www.linkedin.com/in/grandheprasanth",
    g_link: "https://github.com/prasanthgrandhe",
  },

  {
    id: 10,
    img: girl,
    name: "Harshitha A Reddy",
    skill1: "Front End Development",
    skill2: "Python",
    skill3: "C++",
    skill4: "Java",
    l_link: "https://www.linkedin.com/in/harshitha-a-reddy/",
    g_link: "https://github.com/harshithamar",
    t_link: "https://twitter.com/harshithamar",
  },
  {
    id: 11,
    img: boy,
    name: "Aditya Prasad",
    skill1:"Web Developer (Novice)",
    skill2:"Cloud (GCP)",
    skill3:"Python",
    skill4:"Java",
    l_link:"https://www.linkedin.com/in/aditya-panigrahy-59bba8192/",
    g_link:"https://github.com/aditya687",
    t_link:"https://twitter.com/AdityaP35096998",
  },

  {
    id: 12,
    img: girl,
    name: "Amitha Kamath",
    skill1: "Biotech",
    skill2: "Content Writing",
    l_link: "https://www.linkedin.com/in/amitha-kamath-0b5010211,"
  },

  {
    id: 13,
    img: boy,
    name:"Lingaraj Sahu",
    skill1:"C",
    skill2:"C++",
    skill3:"Python",
    skill4:"HTML",
    l_link:"www.linkedin.com/in/lingarajsahu",
    g_link:"https://github.com/lingaraj281",
    t_link:"https://twitter.com/Lingara24759434",
  },

  {
    id: 14,
    img: girl,
    name: "Dipika Ray",
    skill1: "HTML",
    skill2: "CSS(learning)",
    skill3: "Java",
    skill4: "C++",
    l_link: "https://www.linkedin.com/in/dipika-ray-503b68214/",
    g_link: "https://github.com/dia2git",
  },
  {
    id: 15,
    img: boy,
    name :"Siddharth Parashar",
    skill1: "C",
    skill2: "C++",
    skill3: "Git/Github",
    skill4: "JS",
    l_link: "https://www.linkedin.com/in/sp2001/",
    g_link: "https://github.com/sidparashar2001",
  },

  {
    id: 16,
    img: girl,
    name: "ANSHIKA SINGH",
    skill1: "FULL STACK WEB DEVELOPER",
    skill2: "ANDROID DEVELOPER",
    skill3: "PYTHON CODER",
    skill4: "JAVA,C",
    l_link: "https://www.linkedin.com/in/anshika-singh-b50488188",
    g_link: "https://github.com/singhanshika311/",
  },
  {
    id: 17,
    img: boy,
    name :"Lavish Arora",
    skill1: "C/C++",
    skill2: "Web Devepoler (biginner)",
    skill3: "HTML",
    skill4: "CSS",
    l_link: "https://www.linkedin.com/in/lavish-arora-30/",
    g_link: "https://github.com/Lavisharora30",
    t_link: "https://twitter.com/Lavish_arora_30",
  },

  {
    id: 18,
    img: girl,
    name: "Anutoshi",
    skill1: "Java",
    skill2: "HTML",
    skill3: "CSS",
    skill4: "SQL",
    l_link: "https://www.linkedin.com/in/anutoshi-9359aa188",
    g_link: "https://github.com/anutoshi111",
  },

  {
    id: 19,
    img: boy,
    name: "Pradeep Kumar Jaiswal",
    skill1: "C",
    skill2: "C++",
    skill3: "Python",
    skill4: "HTML,CSS",
    l_link: "https://www.linkedin.com/in/pradeep-kumar-jaiswal-b403a61a1",
    g_link: "https://github.com/pkj19",
    t_link: "https://mobile.twitter.com/Pradeep02716281",
  },

  {
    id: 20,
    img: girl,
    name: "N.M.Gowshika",
    skill1: "HTML",
    skill2: "CSS",
    skill3: "Java",
    skill4: "python",
    l_link: "https://www.linkedin.com/in/gowshika-n-m-1316121ba",
    g_link: "https://github.com/gowshika111",
  },

  {
    id: 21,
    img: boy,
    name: "Paras Gupta",
    skill1: "HTML",
    skill2: "C",
    skill3: "Digital marketing",
    skill4: "C++",
    l_link: "https://www.linkedin.com/in/parasshares",
    g_link: "https://github.com/Parasguptas",
  },
  {
    id: 22,
    img: girl,
    name :"Sushma Kulkarni",
    skill1: "c",
    skill2: "html",
    l_link: "https://www.linkedin.com/in/sushma-kulkarni-022229191/",
    g_link: "https://github.com/sushma2108",
  },

  {
    id: 23,
    img: boy,
    name:"Suraj Landage",
    skill1:"Java",
    skill2:"HTML",
    skill3:"CSS",
    skill4:"C",
    l_link:"https://www.linkedin.com/in/surajlandage",
    g_link:"https://github.com/mortallll",
  },

  {
    id: 24,
    img: girl,
    name: "SAUMYA SRIVASTAV",
    skill1: " WEB DEVELOPER (BEGINNER)",
    skill2: "HTML",
    skill3: "CSS",
    skill4: "C",
    l_link: "https://www.linkedin.com/in/saumya-srivastav-4238a91a8",
    g_link: "https://github.com/Saumya2001-PSIT/",
  },
  {
    id: 25,
    img: boy,
    name:"Shivam",
    skill1:"Java",
    skill2:"HTML",
    skill3:"CSS",
    skill4:"C",
    g_link:"https://github.com/Shivam-programmer",
  },
  {
    id: 26,
    img: girl,
    name:"SWATHI A",
    skill1:" WEB DEVELOPER (BEGINNER)",
    skill2:"HTML",
    skill3:"CSS",
    skill4:"C",
    l_link:"https://www.linkedin.com/in/swathi-a-9857841a5",
    g_link:"https://github.com/swathi-469",
    t_link:"https://mobile.twitter.com/SwathiA94998471",
  },

  {
    id: 27,
    img: boy,
    name: "Anurag sharma",
    skill1: "Java" ,
    skill2: "android",
    skill3: "CSS",
    skill4: "C",
    g_link: "https://github.com/anuragsharma8174",
  },

  {
    id: 28,
    img: girl,
    name: "Shubhangi Trivedi",
    skill1: "C/C++",
    skill2: "Web Devepoler (biginner)",
    skill3: "HTML",
    skill4: "CSS",
    g_link: "https://github.com/SHUBHANGITRIVEDI",
  },

  {
    id: 29,
    img: boy,
    name: "Honey Baranwal",
    skill1: "C++",
    skill2: "Python",
    skill3: "HTML",
    skill4: "C",
    l_link: "https://www.linkedin.com/in/honey-baranwal-398904202/",
    g_link: "https://github.com/Honey-B-263 /",
  },

  {
    id: 30,
    img: girl,
    name: "Ishita",
    skill1: "HTML",
    skill2: "JavaScript",
    skill3: "CSS",
    skill4: "C++",
    g_link: "https://github.com/ishita1427",
  },
  {
    id: 31,
    img: boy,
    name: "Shiv Ghosh",
    skill1: "Java",
    skill2: "android",
    skill3: "CSS",
    skill4: "C",
    g_link: "https://github.com/shivghosh8",
  },

  {
    id: 32,
    img: girl,
    name: "Vanshika",
    skill1: "C++",
    skill2: "HTML",
    skill3: "CSS",
    skill4: "C",
    g_link: "https://github.com/GUPTAVANSHIKA",
  },

  {
    id: 33,
    img: boy,
    name: "G.Rohit",
    skill1: "HTML",
    skill2: "JavaScript",
    skill3: "CSS",
    skill4: "C++",
    g_link: "https://github.com/rohit1427",
  },

  {
    id: 34,
    img: boy,
    name :"Shashank",
    skill1: "Python",
    skill2: "Data Science",
    skill3: "HTML",
    skill4: "CSS",
    g_link: "https://github.com/Shashankkrj",
  },

  {
    id: 35,
    img: boy,
    name :"Adarsh Ranjan",
    skill1: "C++",
    skill2: "Cyber Security",
    skill3: "HTML5",
    skill4: "CSS3",
    g_link: "https://github.com/adarshranjan12",
    l_link: "https://www.linkedin.com/in/adarsh-ranjan/",
  },
  {
    id: 36,
    img: girl,
    name :"Arpita",
    skill1: "C",
    skill2: "C++",
    skill3: "HTML5",
    skill4: "CSS3",
    g_link: "https://github.com/ArpitaNag",
  },
  {
    id: 37,
    img: boy,
    name :"Priyangshu",
    skill1: "C",
    skill2: "C++",
    skill3: "HTML 5",
    skill4: "CSS 3",
    g_link: "https://github.com/General-Xamor",
  },
]

export default ContributorData
